# Generated by Django 2.0.1 on 2018-02-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20180215_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
