version: '3'
 
services:
  web:
    container_name: django-api
    build: 
      context: .
      dockerfile: DockerfileAPI
    command: python3 manage.py runserver --settings=api.settings 0.0.0.0:8000
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links: 
      - db

  db:
    container_name: postgres-db
    image: postgres
    restart: always
    volumes:
      - ./artifacts/*.pgsql:/var/lib/postgresql/data/

      # Vue.js application
  frontend:
    container_name: vue-frontend
    build: .
    ports:
      - 8081:8081
    volumes:
      - ./:/app
    command: npm run dev
    depends_on: 
      - web

volumes:
    app:
    artifacts: