# Generated by Django 2.2.1 on 2019-05-15 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('short_title', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=5)),
                ('lst_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('bio_pic', models.ImageField(null=True, upload_to='')),
                ('member_id', models.CharField(blank=True, max_length=20)),
                ('lng_title', models.CharField(blank=True, max_length=50)),
                ('party', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('bill_id', models.CharField(max_length=50)),
                ('vote', models.CharField(max_length=1000)),
                ('results', models.CharField(max_length=1000)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='endpoints.Senator')),
            ],
        ),
    ]
