# Generated by Django 2.0.1 on 2018-02-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip', models.TextField()),
                ('vote', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='party',
            name='senators',
        ),
        migrations.AddField(
            model_name='senator',
            name='member_id',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Party',
        ),
        migrations.AddField(
            model_name='vote',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='pages.Senator'),
        ),
    ]
