# Generated by Django 2.0.1 on 2018-02-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_vote_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senator',
            name='lst_update',
            field=models.DateTimeField(null=True),
        ),
    ]
