# Generated by Django 2.0.1 on 2018-02-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180206_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
