# Generated by Django 2.0.1 on 2018-02-21 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20180220_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senator',
            name='missed_votes_pct',
        ),
        migrations.RemoveField(
            model_name='senator',
            name='votes_with_party_pct',
        ),
    ]
