# Generated by Django 2.2 on 2019-04-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('short_title', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=5)),
                ('bio_pic', models.ImageField(null=True, upload_to='')),
                ('member_id', models.CharField(blank=True, max_length=20)),
                ('lng_title', models.CharField(blank=True, max_length=50)),
                ('party', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
