# Generated by Django 2.0.1 on 2018-02-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180202_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='bill_id',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
