# Generated by Django 2.0.1 on 2018-02-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20180215_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='lng_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='senator',
            name='missed_votes_pct',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='senator',
            name='party',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='senator',
            name='votes_with_party_pct',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='senator',
            name='member_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
