# Generated by Django 2.0.1 on 2018-02-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20180227_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='results',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(max_length=1000),
        ),
    ]
