# Generated by Django 2.2.1 on 2019-05-25 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('short_title', models.CharField(max_length=5)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('lst_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('member_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lng_title', models.CharField(blank=True, max_length=50)),
                ('party', models.CharField(blank=True, max_length=50)),
                ('missed_votes_pct', models.FloatField(blank=True)),
                ('votes_with_party_pct', models.FloatField(blank=True)),
                ('contact_url', models.CharField(blank=True, max_length=200, null=True)),
                ('next_election', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
