# Generated by Django 2.0.1 on 2018-02-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('short_title', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=5)),
                ('lst_update', models.DateField(auto_now_add=True)),
                ('bio_pic', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
