# Generated by Django 2.0.1 on 2018-02-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=10)),
                ('senators', models.ForeignKey(on_delete=models.SET('Ind'), related_name='Senator', to='pages.Senator')),
            ],
        ),
    ]
