# Generated by Django 2.0.1 on 2018-02-02 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180202_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senator',
            name='lst_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 0, 1)),
        ),
    ]
