# Generated by Django 2.0.1 on 2018-02-27 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20180226_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senator',
            name='lst_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
