version: '3'

services:
  cc-postgres:
    image: postgres
    volumes:
      - "${DB_VOLUME}"
    environment: 
      LOCAL_DB_USER: "postgres"
      LOCAL_DB_PASSWORD: "postgres"
      # LOCAL_DB_USER: "${DB_USER}"
      # LOCAL_DB_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "cc-postgres"
    ports:
      - "5432:5432"

  django:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "${DJANGO_VOLUME}"
    ports:
      - "8000:8000"
    # environment:
    #   - api_key=${PROPUBLICA_API_KEY}
    depends_on:
      - cc-postgres

  # vue:
  #   container_name: vue
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-FE
  #   volumes:
  #     - '.:/code'
  #     - '/code/node_modules'
  #   ports:
  #     - '8080:8080'